// Explicit semantic allocation reviewed against the current full source.
// These are approved source spans, NOT a heading/keyword classifier.
// Future source changes require a fresh review and an updated bound review ledger.
const m = (id, purpose, dependencies, facets) => ({ id, purpose, dependencies, facets });
export const modules = [
  m('core', 'Canonical precedence, governance, authority, language, evidence and portable continuity invariants.', [], ['information', 'interaction']),
  m('workspace', 'Current-project private identity, protection, ownership and state isolation.', ['core'], ['workspace_identity', 'workspace_switch', 'private_write']),
  m('shared-context', 'Scoped private hints, supersession and conflict-safe shared coordination.', ['workspace'], ['shared_context']),
  m('activation', 'Bindings, thin owned activation adapters and version-neutral global discovery.', ['workspace'], ['activation', 'full_install']),
  m('capabilities', 'Strongest available lifecycle coverage, reuse, stabilization and actual installed probes.', ['activation'], ['capability_change', 'full_install', 'installed_probe']),
  m('cost', 'Free-first selection and justified paid exceptions.', ['core'], ['facility_selection', 'paid_dependency']),
  m('repository', 'Provider-neutral scoped discovery, creation, canonical binding and access.', ['workspace', 'cost'], ['repository_access', 'repository_create']),
  m('security', 'Project-authorized identity, controlled invocation, enrollment and separate access/signing proofs.', ['workspace', 'cost'], ['identity_sensitive', 'credential_change', 'sensitive_effect']),
  m('model', 'Organizational canonical representation, external sources of record and dependency graph.', ['core'], ['organizational_model']),
  m('operations', 'Project canonical operations, foundational intake and publication.', ['repository', 'security', 'model'], ['canonical_read', 'canonical_write', 'full_install']),
  m('inventory', 'Relevant repository inventory and retrieval.', ['operations'], ['inventory_change']),
  m('intake', 'Effective-scope discovery and proportionate clarification.', ['core'], ['request_intake', 'scope_uncertainty']),
  m('impact', 'Effective scope, causal propagation and proportionate new organizational capabilities.', ['model', 'intake'], ['managed_change', 'scope_expansion', 'organizational_evolution']),
  m('tickets', 'Managed work, transition guards, durability, notifications and completion.', ['operations', 'impact', 'history'], ['ticket_mutation', 'durable_work', 'managed_change']),
  m('changes', 'Reviewable change sets, authorized desired state, application and verification.', ['tickets'], ['change_set', 'managed_change']),
  m('execution', 'Intended, attempted, observed, applied and verified effects; informed recovery/retry.', ['core'], ['material_effect', 'verification', 'retry', 'external_effect']),
  m('migration', 'Shared organizational transformation, read/write compatibility, ownership and concurrency.', ['operations', 'changes', 'execution'], ['version_sensitive', 'organizational_migration', 'due_update']),
  m('adoption', 'Bounded source freshness, independent runtime checkpoints and ordered adoption.', ['capabilities', 'migration'], ['due_update', 'adoption_change', 'full_install']),
  m('continuity', 'Budget signals, reliable <=15% reserve and destination-independent preparation.', ['core'], ['continuity_reserve', 'handoff']),
  m('handoff', 'Portable baseline, access continuity and separately evidenced transfer phases.', ['continuity', 'tickets', 'repository', 'security', 'adoption'], ['handoff']),
  m('destination', 'Independent destination intake, resource filtering and source/target firewall.', ['handoff'], ['destination_entry']),
  m('secret-transfer', 'Separate necessary authorized secret transfer; reuse and safe acquisition first.', ['security', 'handoff'], ['secret_transfer']),
  m('recovery', 'Resumable activity and verified context reconstruction after interruption.', ['core', 'workspace', 'context'], ['context_loss', 'interrupted_setup', 'recovery']),
  m('decisions', 'Durable significant decisions, rationale and related work.', ['operations', 'history'], ['decision_record']),
  m('human', 'Actual human-only dependency and automatic verified resumption.', ['core'], ['human_dependency']),
  m('physical', 'Physical-world responsibilities, constraints and observable completion.', ['impact'], ['physical_effect']),
  m('ci', 'Risk-proportionate consistency checks and semantic compilation.', ['changes', 'cost'], ['change_set', 'semantic_propagation']),
  m('delivery', 'Controlled application, risk gates, compensation and drift.', ['changes', 'execution', 'ci', 'cost'], ['deployment', 'external_effect', 'compensation', 'drift']),
  m('history', 'Causal, non-fabricated temporal reconstruction with evidence reuse.', ['core'], ['history_query', 'material_event']),
  m('interfaces', 'Tool-independent external projections over canonical English state.', ['model'], ['external_interface']),
  m('producer', 'Maintainer-only release acceptance, regression, traceability and authorized publication.', ['core'], ['oop_maintenance']),
  m('context', 'Current available action context, selective rehydration and retirement.', ['core'], ['context_loss', 'route_change', 'interaction']),
  m('entry', 'Conversation and per-message gates plus progressive minimum context.', ['workspace', 'context'], ['interaction', 'information']),
  m('bootstrap', 'Full BOOT-01–13 procedure, system obligations, scoped attestation and user communication.', ['entry', 'activation', 'adoption', 'operations', 'capabilities', 'human'], ['full_install', 'interrupted_setup']),
  m('delegation', 'Same-contract delegates, owned controls and validated completion.', ['capabilities', 'context'], ['delegation']),
];
// Every line, including contextual lists/tables and conditional examples, is retained once.
// Semantic allocation crosses source headings (notably core, entry, context and destination).
export const spans = [
  ['mandate-authority',1,75,'core'], ['enforcement-autonomy',76,155,'core'],
  ['delegate-governance',156,159,'delegation'], ['transitions-routing',160,234,'core'],
  ['technology-neutrality',235,277,'core'], ['canonical-language',278,364,'core'],
  ['localized-presentation',365,406,'core'], ['private-boundary',407,463,'workspace'],
  ['shared-coordination',464,498,'shared-context'], ['persistent-activation',499,553,'activation'],
  ['consumer-exclusions',554,561,'core'], ['runtime-adoption',562,640,'adoption'],
  ['capability-lifecycle',641,762,'capabilities'], ['free-first',763,936,'cost'],
  ['repository-bootstrap',937,988,'repository'], ['scoped-credentials',989,1031,'security'],
  ['canonical-operations',1032,1086,'operations'], ['organizational-migration',1087,1149,'migration'],
  ['organizational-model',1150,1298,'model'], ['repository-inventory',1299,1327,'inventory'],
  ['request-discovery',1328,1430,'intake'], ['ticket-lifecycle',1431,1589,'tickets'],
  ['continuity-reserve',1590,1651,'continuity'], ['portable-transfer',1652,1818,'handoff'],
  ['destination-intake',1819,1869,'destination'], ['sensitive-transfer',1870,1991,'secret-transfer'],
  ['handoff-durability',1992,2145,'handoff'], ['asynchronous-recovery',2146,2182,'recovery'],
  ['state-separation',2183,2218,'core'], ['decision-history',2219,2238,'decisions'],
  ['human-prerequisite',2239,2268,'human'], ['physical-organization',2269,2304,'physical'],
  ['impact-propagation',2305,2449,'impact'], ['proportionate-evolution',2450,2467,'impact'],
  ['reviewable-changes',2468,2557,'changes'], ['effect-verification',2558,2589,'execution'],
  ['semantic-ci',2590,2646,'ci'], ['controlled-delivery',2647,2747,'delivery'],
  ['temporal-history',2748,2811,'history'], ['external-projections',2812,2840,'interfaces'],
  ['evidence-reuse',2841,2865,'core'], ['producer-publication',2866,2869,'producer'],
  ['producer-acceptance',2870,2936,'producer'], ['interaction-entry',2937,2966,'entry'],
  ['full-install',2967,2992,'bootstrap'], ['bootstrap-system',2993,3012,'bootstrap'],
  ['bootstrap-attestation',3013,3018,'bootstrap'], ['validity-refresh',3019,3028,'entry'],
  ['available-context',3029,3044,'context'], ['bootstrap-communication',3045,3058,'bootstrap'],
  ['minimum-entry',3059,3071,'entry'], ['continuation-entry',3072,3075,'destination'],
  ['progressive-entry',3076,3091,'entry'], ['portable-final-invariants',3092,3144,'core'],
].map(([id,start,end,module]) => ({ id: `OOP-${id}`, start, end, module }));

export const semanticReview = {
  basis: 'Complete semantic reading of PROTOCOL.md followed by explicit allocation; line spans only locate reviewed clauses. No heading-to-module or keyword inference.',
  preservation: 'All original source wording, scope, exceptions, tables, examples and normative convention are retained verbatim after CRLF-to-LF normalization. Examples retain their non-authorizing status.',
  formalization: 'Structured boundaries refer to complete semantic clauses. They do not decide semantic judgments or manufacture facts. Formal bootstrap guards are necessary checks, not sufficient authorization.',
  coreRationale: 'Precedence, authority, proportionality, language, consumer exclusions, state separation and evidence invariants apply across routes. Entry/context/workspace add current identity and availability; conditional business modules remain on demand.',
  dependencyRationale: 'Dependencies are conservative prerequisites from reviewed meaning. Effectful branches add action/security/execution facets even when a request initially seems informational. Context assembly never grants authority.',
  limitations: ['Semantic review performed by the producing AI; no independent human/second-model approval claimed.', 'No runtime adapter, provider enrollment or consumer installation executed by this package.'],
};
